### GET all characters
http://localhost:3000/api/alumnos

### POST a character
# @name createA
POST http://localhost:3000/api/alumnos
Content-Type: application/json
    
{
    "nombre": "Juan",
    "apellido": "Perez",
    "plan": "98",
    "mail": "juanperez@gmail.com",
    "direccion": "Calle falsa 123",
    "fechaN": "1998-12-12",
    "inscripciones": []
}
### ID
@id = {{createA.response.body.data.id}}

### GET one character
http://localhost:3000/api/alumnos/{{id}}

### PUT a character
PUT http://localhost:3000/api/alumnos/{{id}}
Content-Type: application/json
    
{
    "nombre": "Juan",
    "apellido": "Perez",
    "plan": "01",
    "mail": "juancitop@gmail.com" 
}

### POST a character
POST http://localhost:3000/api/alumnos
Content-Type: application/json

{
    "nombre": "raul",
    "apellido": "Rodriguez",
    "plan": "05",
    "mail": "raulR@gmail.com",
    "direccion": "Calle falsa 321",
    "fechaN": "2001-04-12",
    "inscripciones": []
}


### PATCH a character
PATCH http://localhost:3000/api/alumno/{{idToDelete}}
Content-Type: application/json

{
  "level": 6,
  "characterClass":4,
  "items": [1]
}
        
   

