GET http://localhost:3000/api/alumnos
Content-Type: application/json 

###
GET http://localhost:3000/api/alumnos/a02b9bb1-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

###
POST http://localhost:3000/api/alumnos
Content-Type: application/json

{
    "nombre": "Jorge",
    "apellido": "Martinez",
    "plan": "1998",
    "mail": "jorgemartin@gmail.com",
    "direccion":"salta 1212",
    "fechaN":"11/05/1998"
}

###
PUT http://localhost:3000/api/alumnos/a02b9bb1-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "nombre": "Jorge Alberto",
    "apellido": "Martinez Gomez",
    "plan": "2003",
    "mail": "jorgemartin98@gmail.com",
    "direccion":"salta 1998",
    "fechaN":"11/06/1998"
}

###
PATCH http://localhost:3000/api/alumnos/a02b9bb1-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "mail": "jorgemartin1998@gmail.com"
}

###
DELETE http://localhost:3000/api/alumnos/a02b9bb1-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json